appName:  Dropwizard Scaffolding App
swaggerBundleConfiguration:
  resourcePackage: sample
  schemes:
    - http
server:
  rootPath: /*
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8100
  gzip:
      enabled: false
logging:
  level:  WARN
  loggers:
    cci:  INFO